# This is a basic workflow that is manually triggered

name: Delta - No Tests
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: 'If DEBUGGING and artifact creation should be enabled'
        default: false
        required: false
        type: boolean
      PLSPROD:
        description: 'Use production PLS Endpoint'
        default: false
        required: false
        type: boolean
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generic-deploy-without-test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Add Input Options to Summary
        run: |
          echo '# Deployment Summary for ${{github.ref_name}}' >> $GITHUB_STEP_SUMMARY
          echo '## Input Options' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJson(github.event.inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
